### ISSUE TITLE
Error encountered with az iot hub device-identity create

### ISSUE THREAD

**Issue by v-gpettibone** [Azure/azure-iot-cli-extension#379] opened 2021-06-25 18:36 UTC
## Describe the bug

**Command Name**
`az iot hub device-identity create
Extension Name: azure-iot. Version: 0.10.7.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'IotHubResourceOperations' object has no attribute 'config'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/greg/.azure/cliextensions/azure-iot/azext_iot/operations/hub.py", line 139, in iot_device_create
    hub_name=hub_name, resource_group_name=resource_group_name, login=login
  File "/home/greg/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 136, in get_target
    target_iothub = self.find_iothub(hub_name=hub_name, rg=rg)
  File "/home/greg/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 72, in find_iothub
    self._initialize_client()
  File "/home/greg/.azure/cliextensions/azure-iot/azext_iot/iothub/providers/discovery.py", line 35, in _initialize_client
    self.sub_id = self.client.config.subscription_id
AttributeError: 'IotHubResourceOperations' object has no attribute 'config'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-identity create -n {} -d {}`

## Environment Summary
```
Linux-5.4.0-1048-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.25.0
azure-cli-iot-ext 0.8.10

Extensions:
azure-iot 0.10.7
azure-cli-iot-ext 0.8.10
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by c-ryan-k** [comment] 2021-06-25 22:31
Hey @v-gpettibone - upgrading your extension is the solution here.

I also noticed you have multiple versions of the IoT extension installed:
> azure-iot 0.10.7
azure-cli-iot-ext 0.8.10

You'll want to uninstall the first one with `az extension remove --name azure-cli-iot-ext`
And then update the second one with `az extension update --name azure-iot`

**Comment by v-gpettibone** [comment] 2021-06-25 22:33
Great. Thanks for the help, Ryan.

**Comment by digimaun** [comment] 2021-06-28 22:11
Closing issue since the root cause and solution have been identified. If after applying the recommended solution you run into issues, you can comment here and we will re-open.

**Closed by digimaun** 2021-06-28 22:11 UTC
