### ISSUE TITLE
ERROR: The command requires the extension azure-iot.

### ISSUE THREAD

**Issue by tharakram** [Azure/azure-iot-cli-extension#290] opened 2020-12-15 02:11 UTC
Hello,

I am creating a CI/CD pipeline in Jenkins to deploy the custom Edge solutions into my Edge devices. I am new to the Azure IoT CLI extensions. I have installed the CLI and the IoT extensions in my Jenkins host. When I build the pipeline, it is failing while executing the below command. I have verified the extensions installation and checked the versions. Everything is configured as per the plugin documentation and the CLI extension wiki page.

iotedgedev genconfig --file deployment.template.json --platform amd64

Below is the error message:
ERROR: The command requires the extension azure-iot.
 Unable to prompt for extension install confirmation as no tty available. Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt.

Finished: FAILURE

**Environment:**

- OS: Linux QuickstartJenkins-vm 5.4.0-1034-azure #35~18.04.1-Ubuntu SMP Thu Dec 10 09:13:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Shell: bash
- Az CLI version: 2.16.0
- IoT extension version: 0.10.7
- Python version (if pip installed): pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

**Additional context**
The pipeline is a Free Style project

**Comment by digimaun** [comment] 2020-12-15 02:40
Hey @tharakram , thanks for submitting this issue. `iotedgedev` is a higher level tool that consumes the IoT extension for az cli and related az cli commands. So potentially this is an issue originating in that tool and here is the [repo for it](https://github.com/Azure/iotedgedev/issues).

First I would recommend validating the underlying az cli and extension are working properly. You can run: `az extension list` to determine what extension are installed. IoT wise there should be a single extension called `azure-iot` (and version 0.10.7 as you indicated). IF it exists, `azure-cli-iot-ext` was a legacy iot extension and should be removed. Another quick check, is to run any IoT CLI command in your environment - for example `az iot hub device-identity create`. Idea is to rule out (or not) where this seeming config issue stems from. Please let us know of these findings.

**Comment by tharakram** [comment] 2020-12-15 06:12
Hi Digimaun,

Thank you for the prompt response. I have double checked the extension list, I see <azure-iot> exist and I have removed the legacy <azure-cli-iot-ext> extension. 

I have checked IoT CLI in my environment by executing the <az iot hub device-identity create -n <reg> -d <device `id>>.` Initially it prompted me to install <azure-iot> even though it was already installed in the host. Below is the message appeared after executing above command. After accepting, it created a device successfully.

The command requires the extension azure-iot. Do you want to install it now? The command will continue to run after the extension is installed. (Y/n): Y
Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt.

So I guessed it must be something to do with the access privileges of Jenkins account as the azure-iot is installed as root on the host. It worked after installing the azure-iot for user <jenkins>.

**Comment by digimaun** [comment] 2020-12-16 01:49
Thanks for following up Tharakram. Glad we've made a bit of progress.

Good idea on the access privileges of the Jenkins account. For what its worth, typical extension installs for Azure CLI get installed in the user space `~/.azure/cliextensions` by default. You should be able to change this via env var `AZURE_EXTENSION_DIR`. So one experiment (if you wanted to keep the root host install) is to try to point to the root extensions directory.

One other thing to point out `az config set` is actually experimental (you can verify appending `--help` to the command). Assuming this is a configuration option set by `iotedgedev`.

**Comment by digimaun** [comment] 2020-12-17 21:21
Going to close this issue for now as it appears the root cause was identified. Feel free to comment here and we can continue the discussion.

**Closed by digimaun** 2020-12-17 21:21 UTC

**Comment by tharakram** [comment] 2020-12-18 18:32
Thank you @digimaun my apologies I couldn't respond early. Yes, changing the configs and permissions fixed the issue. Thank you for the quick help.
