### ISSUE TITLE
Error with SAS URI for az iot hub device-identity export

### ISSUE THREAD

**Issue by vsaroopchand** [Azure/azure-iot-cli-extension#79] opened 2019-06-28 15:49 UTC
We are facing an issue with `az iot hub device-identity export --bcu
                                  --hub-name
                                  [--ik {false, true}]
                                  [--resource-group]`, particularly with --bcu

When we execute the above command with SAS URI w/ all resources and all permissions, we get "Unable to access blob"

When we execute the above command with --bcu as the first argument it seems to cause all other flags to be missed. This all suggest an issue with the URI causing some issues parsing the arguments. Can someone please test this and confirm if its working? I can send snapshots of our commands.

**Comment by vsaroopchand** [comment] 2019-07-01 14:42
Any updates on this issue? I encoded my SAS Token which resolved the original error; however, now I am getting max retry timeouts.

az : ERROR: The command failed with an unexpected error. Here is the traceback:
At line:1 char:1
+ az iot hub device-identity export --ik true --bcu "https%3A%2F%2Fsita ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: The comm... the traceback::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
ERROR: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: 
/subscriptions/5819708a-8677-48d1-b909-9e2af352c96e/resourceGroups/delme-storage/providers/Microsoft.Devices/IotHubs/testexport/exportDevices?api-version=2018-12-01-preview (Caused by ResponseError('too 
many 500 error responses',))
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\requests\requests\adapters.py", line 449, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\urllib3\urllib3\connectionpool.py", line 731, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\urllib3\urllib3\connectionpool.py", line 731, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\urllib3\urllib3\connectionpool.py", line 731, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\urllib3\urllib3\connectionpool.py", line 711, in urlopen
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\urllib3\urllib3\util\retry.py", line 398, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: 
/subscriptions/5819708a-8677-48d1-b909-9e2af352c96e/resourceGroups/delme-storage/providers/Microsoft.Devices/IotHubs/testexport/exportDevices?api-version=2018-12-01-preview (Caused by ResponseError('too 
many 500 error responses',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\msrest\msrest\universal_http\requests.py", line 137, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\requests\requests\adapters.py", line 507, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: 
/subscriptions/5819708a-8677-48d1-b909-9e2af352c96e/resourceGroups/delme-storage/providers/Microsoft.Devices/IotHubs/testexport/exportDevices?api-version=2018-12-01-preview (Caused by ResponseError('too 
many 500 error responses',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 351, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 409, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 402, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 379, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-cli-core\azure\cli\core\__init__.py", line 451, in default_command_handler
  File "C:\Users\vishal\.azure\cliextensions\azure-cli-iot-ext\azext_iot\operations\hub.py", line 1255, in iot_device_export
    return client.export_devices(target['resourcegroup'], hub_name, blob_container_uri, not include_keys)
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\azure-mgmt-iothub\azure\mgmt\iothub\operations\iot_hub_resource_operations.py", line 1677, in export_devices
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-instal
l-qvpg2q31\msrest\msrest\service_client.py", line 336, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\msrest\msrest\pipeline\__init__.py", line 197, in run
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\msrest\msrest\pipeline\__init__.py", line 150, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\msrest\msrest\pipeline\requests.py", line 72, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\msrest\msrest\pipeline\requests.py", line 137, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\msrest\msrest\pipeline\__init__.py", line 150, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\msrest\msrest\pipeline\requests.py", line 193, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\msrest\msrest\universal_http\requests.py", line 328, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\msrest\msrest\universal_http\requests.py", line 140, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\msrest\msrest\exceptions.py", line 51, in raise_with_traceback
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\msrest\msrest\universal_http\requests.py", line 137, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\requests\requests\sessions.py", line 533, in request
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\requests\requests\sessions.py", line 646, in send
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qvpg2q31\requests\requests\adapters.py", line 507, in send
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: 
/subscriptions/5819708a-8677-48d1-b909-9e2af352c96e/resourceGroups/delme-storage/providers/Microsoft.Devices/IotHubs/testexport/exportDevices?api-version=2018-12-01-preview (Caused by ResponseError('too 
many 500 error responses',))
WARNING: 
To open an issue, please visit: https://aka.ms/azcli/ext/issues

**Comment by digimaun** [comment] 2019-07-09 22:21
Hey @vsaroopchand. The root of this problem likely stems from your shell. It looks like you are using powershell?

If so do something like this to prevent powershell from tripping up:

`az iot hub device-identity export --bcu --% "<your full sas token>" --hub-name <your hub  name>`

Note: The SAS token placeholder in my example is the original URL format copied out of storage explorer with no modification.

Can you try that and let us know how it goes?

**Comment by digimaun** [comment] 2019-07-18 19:05
Closing issue as the problem is repro'able on the presumed target shell (powershell) and usage of `--%` resolves parsing issues.

Please re-open this issue to discuss further.

**Closed by digimaun** 2019-07-18 19:05 UTC
