### ISSUE TITLE
Error 403.043.004.005 getting tokens.

### ISSUE THREAD

**Issue by AbdelhakimDAOUDI** [Azure/azure-iot-cli-extension#144] opened 2020-03-10 19:46 UTC
Hello,

I would like to monitor telemetry received by my IoT Central Application using the following command:

> az iot central app monitor-events --app-id xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

I got this Error :

> Error 403.043.004.005 getting tokens. User principals must get tokens from the common tenant.

FYI, login using my account is successful.

I don't understand this error and no information can be found on it.

Any help, please

**Comment by Jackbk** [comment] 2020-03-10 19:55
Hi @AbdelhakimDAOUDI ,

To get tokens for IoTC, you will need to be logged in to Azure CLI (az login), but also be configured for your home tenant.  

Please try:
`az login --tenant **yourdir**.onmicrosoft.com`

Regards,
Jack

**Comment by AbdelhakimDAOUDI** [comment] 2020-03-10 20:50
Thank you for your help @Jackbk.

I tried the command but the error is still present.
After executing the command, this message was displayed:

> You have logged in. Now let us find all the subscriptions to which you have access...

followed by json informations of my account.

Do I have to set up something on Azure Portal?

Regards,

**Comment by digimaun** [comment] 2020-03-10 21:28
@AbdelhakimDAOUDI , just to double check, make sure the right account subscription is activated using `az account set -s '<subscription guid>'`. Your central app may be in a different subscription than the activated one.

**Comment by digimaun** [comment] 2020-03-12 23:49
@AbdelhakimDAOUDI did you resolve the issue?

**Comment by AbdelhakimDAOUDI** [comment] 2020-03-13 15:38
@digimaun Still the same error.

I entered the following commands:

```
az login --tenant [MYDIR].onmicrosoft.com
az account set -s [ACCOUNT-ID]
az iot central app monitor-events --app-id [APP-ID]

```
I'm sure `[MYDIR]`, `[ACCOUNT-ID]` and `[APP-ID]` are correct.
I got them from Azure portal.

Any idea?

**Comment by Jackbk** [comment] 2020-03-13 18:35
Hi @AbdelhakimDAOUDI ,

One other thing to clarify, in my previous response I suggested you use your tenant on login. IoT Central is a little different to other azure resources,  tenant needs to be the one where your user account was created (not the one where the app was created).  

Can you please verify this?

**Comment by AbdelhakimDAOUDI** [comment] 2020-03-13 19:05
Hi,

I confirm the tenant I entered is the one where the user was created.
When I enter the command I have the JSON this message :

> You have logged in. Now let us find all the subscriptions to which you have access...

followed by JSON values:

```
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "id": "xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "isDefault": true,
    "managedByTenants": [],
    "name": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "state": "Enabled",
    "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "user": {
      "name": "xxxxxx@xxxxx.xxx",
      "type": "user"
    }
  }
]
```

`homeTenantId` and `tenantId` have the same value.

I asked a colleague to try with his account.

I will let you know the result of his try ASAP.

Regards

**Comment by MateRadz** [comment] 2020-03-17 10:17
Any progress on this issue? As I have the same exact problem. Tried changing to every subscription and the same problem appears.

**Comment by AbdelhakimDAOUDI** [comment] 2020-03-17 11:28
Hello,

I tried with a colleague account and it worked.

The only difference I can notice is my role is assigned to "guest" on Azure Access control (IAM).

Hope this helps.

**Comment by MateRadz** [comment] 2020-03-17 11:44
I have a contributor role on this subscription, so I guess it does not help.


________________________________
Od: AbdelhakimDAOUDI <notifications@github.com>
Wysłane: wtorek, 17 marca 2020 12:28
Do: Azure/azure-iot-cli-extension <azure-iot-cli-extension@noreply.github.com>
DW: Mateusz Radziszewski <mradziszewski@eip.pl>; Comment <comment@noreply.github.com>
Temat: Re: [Azure/azure-iot-cli-extension] Error 403.043.004.005 getting tokens. (#144)


Hello,

I tried with a colleague account and it worked.

The only difference I can notice is my role is assigned to "guest" on Azure Access control (IAM).

Hope this helps.

**Comment by Jackbk** [comment] 2020-04-13 18:44
Hi @MateRadz  did you manage to resolve this issue?

Some things to note when using the CLI for IoT Central:
- user must be logged in via commandline
- user must have the correct tenant set (user account tenant)
- user must have access to the app

**Comment by MateRadz** [comment] 2020-04-14 07:11
... I stopped trying, as I the root cause disappeared (I wanted to troubleshoot the device, because I was not receiving telemetry - but now it works). But I think I was not logged in via commandline.

**Comment by digimaun** [comment] 2020-04-14 22:04
Thanks for that additional info @MateRadz . Going to close this issue as @Jackbk provided our [set of recommendations for troubleshooting](https://github.com/Azure/azure-iot-cli-extension/issues/144#issuecomment-613036439) when running into issues with the command.

If anyone else still has problems even after going through troubleshooting checklist, then you can create a new issue, or comment here and we can re-open this one.

**Comment by Y07yoyo** [comment] 2020-04-20 22:40
Hi,
I am having the following isssue when I run this command:
Command: az iot central app monitor-events --app-id xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --properties all
Error: Error 403.043.004.005 getting tokens. User principals must get tokens from the common tenant.

I have logged in on the cmd using az login. I get the following details:
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Pay-As-You-Go",
    "state": "Enabled",
    "tenantId": "xxxxxxxxxxxxxxxxxxxxxx",
    "user": {
      "name": "xxxxxxxxxxx",
      "type": "user"
    }
  }
]
Home Tentant ID and TenandID are the same. I have access to the app on IOT Central and my role is Administrator.
Can you please advice?

**Comment by Y07yoyo** [comment] 2020-04-20 23:19
Just to clarify a bit more:
My Colleague has the Azure subscription which is pay-as-you-go. He added me as a guest but I have all the same priviledges.. In IAM I am an Owner and co-Administrator.
I have signed into Azure CLI with the Tenant ID that has the subscription. Since my colleague created the IOT Central App, in IOT Central -> Administration -> Users, I am Administrator as well.

**Comment by Jackbk** [comment] 2020-04-28 19:37
Hi @Y07yoyo,

Could you please clarify whether your account is an MSA account or an AAD account?

**Comment by digimaun** [comment] 2020-05-12 17:36
Closing due to lack of activity.

**Closed by digimaun** 2020-05-12 17:36 UTC
Labels: central
