### ISSUE TITLE
`hub module-twin update` fails with 404 for $edgeHub

### ISSUE THREAD

**Issue by crpietschmann** [Azure/azure-iot-cli-extension#129] opened 2019-12-16 22:24 UTC
**Steps to Reproduce**
Run the following command to add a new Desired Property to the Module Twin for the $edgeHub module of an IoT Edge Device:

```sh
az iot hub module-twin update --hub-name MyIoTHub --device-id IoTEdgeGateway --module-id "$edgeHub" --add properties.desired.storeAndForwardConfiguration.timeToLiveSecs=14400
```

**Expected Result**
It should set the `storeAndForwardConfiguration.timeToLiveSecs` Desired Property on the Module Twin of the $edgeHub module to the specified value.

**Result Returned**
It returns the following error message:

```
404 Client Error: Not Found for url: https://myiothub.azure-devices.net/twins/IoTEdgeGateway/modules/?api-version=2018-08-30-preview
```

Why would the underlying ARM REST API return a 404 for the $edgeHub module fo the IoT Edge Device? The $edgeHub module is clearly registered with the IoT Edge Device, and it does show up within the Azure Portal.

is there any current way to use the Azure CLI to update the Desired Properties of the $edgeHub module on an IoT Edge Device?

**Comment by digimaun** [comment] 2019-12-17 00:26
Hey @crpietschmann. Which shell are you using? `$` has special meaning in many shells - so you need to ensure the system module name is escaped so its interpreted as a literal. For example if you are using powershell you can do `'$edgeHub'` instead of `"$edgeHub"` for --module-id. Generally you'd want to use --set as well. --add is used for adding an element to an existing collection.

All this being said, I don't think you will be able to achieve the desired effect due to API constraints. Take a look at [this issue](https://github.com/Azure/iotedge/issues/1162) here for more explanation.

To go down the solution path of the linked issue, you can use `az iot edge set-modules` which uses the apply configuration API.

**Comment by crpietschmann** [comment] 2019-12-17 18:42
@digimaun Thanks for the suggestions. I was able to get further with a command that appears that is should work, but returns an error message that looks to be uncovering a bug in the API.

When I run the following command:

```sh
az iot hub module-twin update --hub-name MyIoTHub --device-id IoTEdgeGateway --module-id "\$edgeHub" --add properties.desired.storeAndForwardConfiguration.timeToLiveSecs=12345
```

The `\` can be used to escape `$` in bash, and this command seems to submit the command to update `timetoLiveSecs` as I would like too, however the CLI return the below error message.

It returns this error message:

```text
Couldn't find 'timeToLiveSecs=12345' in 'properties.desired.storeAndForwardConfiguration'. Available options: ['timeToLiveSecs']
```

Since I'm specifying `timeToLiveSecs` and the error message is telling me it couldn't find it and `timeToLiveSecs` is an available option, this looks to be a bug in the API.

Would you be able to look into this or pass it along to the appropriate team?

**Comment by digimaun** [comment] 2019-12-30 20:03
Looping back on this issue...the error you mentioned is by design. The API will not let you patch the system module property (the prior mentioned/referenced issue confirms this is by design). For this use case, you have to use `az iot edge set-modules` to update the edgeHub twin.

**Comment by digimaun** [comment] 2020-01-08 19:29
Closing since the discussion seems resolved. Feel free to comment and we can re-open.

**Closed by digimaun** 2020-01-08 19:29 UTC
