### ISSUE TITLE
az iot edge deployment create fails due to missing jsonschema distribution on Azure Hosted VS2017 agents

### ISSUE THREAD

**Issue by tristanbarcelon** [Azure/azure-iot-cli-extension#95] opened 2019-09-18 14:24 UTC
Azure Hosted VS2017 agents now fail to deploy iot edge modules starting Sep 18 with these errors:

```
2019-09-18T10:18:41.8898408Z ERROR: The 'jsonschema' distribution was not found and is required by the application
2019-09-18T10:18:41.8898990Z Traceback (most recent call last):
2019-09-18T10:18:41.8899388Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\knack\knack\cli.py", line 206, in invoke
2019-09-18T10:18:41.8899804Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 603, in execute
2019-09-18T10:18:41.8900242Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 661, in _run_jobs_serially
2019-09-18T10:18:41.8900631Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 654, in _run_job
2019-09-18T10:18:41.8901222Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\six\six.py", line 693, in reraise
2019-09-18T10:18:41.8901619Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 631, in _run_job
2019-09-18T10:18:41.8902357Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
2019-09-18T10:18:41.8902812Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-xo02umyl\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
2019-09-18T10:18:41.8903309Z   File "C:\Program Files\Common Files\AzureCliExtensionDirectory\azure-cli-iot-ext\azext_iot\operations\hub.py", line 524, in iot_edge_deployment_create
2019-09-18T10:18:41.8903727Z     login=login, edge=True)
2019-09-18T10:18:41.8904167Z   File "C:\Program Files\Common Files\AzureCliExtensionDirectory\azure-cli-iot-ext\azext_iot\operations\hub.py", line 558, in _iot_hub_configuration_create
2019-09-18T10:18:41.8904585Z     content = _process_config_content(content, 'module' if edge else 'device')
2019-09-18T10:18:41.8905039Z   File "C:\Program Files\Common Files\AzureCliExtensionDirectory\azure-cli-iot-ext\azext_iot\operations\hub.py", line 613, in _process_config_content
2019-09-18T10:18:41.8905641Z     _validate_payload_schema(content)
2019-09-18T10:18:41.8906203Z   File "C:\Program Files\Common Files\AzureCliExtensionDirectory\azure-cli-iot-ext\azext_iot\operations\hub.py", line 626, in _validate_payload_schema
2019-09-18T10:18:41.8908530Z     from jsonschema import validate
2019-09-18T10:18:41.8909016Z   File "C:\Program Files\Common Files\AzureCliExtensionDirectory\azure-cli-iot-ext\jsonschema\__init__.py", line 33, in <module>
2019-09-18T10:18:41.8909404Z     __version__ = get_distribution(__name__).version
2019-09-18T10:18:41.8909814Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\pkg_resources\__init__.py", line 472, in get_distribution
2019-09-18T10:18:41.8910207Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\pkg_resources\__init__.py", line 344, in get_provider
2019-09-18T10:18:41.8910773Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\pkg_resources\__init__.py", line 892, in require
2019-09-18T10:18:41.8911766Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\lib\site-packages\pkg_resources\__init__.py", line 778, in resolve
2019-09-18T10:18:41.8912502Z pkg_resources.DistributionNotFound: The 'jsonschema' distribution was not found and is required by the application
```

I suspect that the azure build agent image was changed to include updated dependencies for azure-cli-iot-ext because on Sep 17th we were able to deploy just fine without any errors. There's a [jsonschema validation issue](https://github.com/Azure/azure-iot-cli-extension/issues/84) logged last month. Could the fix for issue 84 have driven the change in azure-cli-iot-ext to include jsonschema validation prematurely.

**Comment by jaryder** [comment] 2019-09-18 20:23
I am hitting the same issue.  Looks like the new jsonschema dependency isn't getting pulled down automatically or doesn't exist.
Version 0.8.0 does not contain jsonschema under "run_requires"
Version 0.8.1 contains jsonschema~=3.0.2

**Comment by jaryder** [comment] 2019-09-18 21:21
I have tried installing the minimum required version of jsonschema and that did not resolve the issue.

**Comment by jaryder** [comment] 2019-09-18 21:44
You can unblock yourself by using the following to install azure-cli-iot-ext (be sure to remove the extension first if it's already installed):
az extension add --source https://github.com/Azure/azure-iot-cli-extension/releases/download/v0.8.0/azure_cli_iot_ext-0.8.0-py2.py3-none-any.whl

**Comment by tristanbarcelon** [comment] 2019-09-18 23:18
This issue happens on Azure hosted agents. Would the az extension command override version 0.8.1 that is installed on the agents?

**Comment by tristanbarcelon** [comment] 2019-09-19 11:20
@jaryder , how'd you install jsonschema? Did you use `pip install jsonschema==3.0.2` ?

**Comment by bramkl** [comment] 2019-09-19 14:51
Hi @jaryder and @tristanbarcelon,

I'm experiencing the same issue. Unfortunately, installing v0.8.0 on the agent did not solve it. 

I'm using an Azure CLI task in the release pipeline with the following command: 
`az extension add --source https://github.com/Azure/azure-iot-cli-extension/releases/download/v0.8.0/azure_cli_iot_ext-0.8.0-py2.py3-none-any.whl --verbose --yes`

There's no other version installed; `az extension remove -n azure-cli-iot-ext`  results in an error that it cannot find the installation

Agent is Unbuntu 16.04

**Comment by jaryder** [comment] 2019-09-19 15:18
@tristanbarcelon I added it a requirements.txt file (essentially, pip install) that we have.  However, it made no difference.  Perhaps the cli extension is expecting to find it elsewhere.

@bramkl I'm also running on an Ubuntu 16.04 agent.  I install the azure-cli-iot-ext as part of a bash script run to set up our environment.  I can confirm that it is working with version v0.8.0.

**Comment by digimaun** [comment] 2019-09-19 19:04
Version 0.8.2 (just released) should resolve this issue. It may take a day or two from now for the cli extension index to update.

**Comment by digimaun** [comment] 2019-09-23 19:48
Quick follow up - the extension index PR was merged Sept 20th 2019, 4:36 PM EDT. So considering this issue resolved.

Please reopen if still running into problems.

**Closed by digimaun** 2019-09-23 19:48 UTC
