### ISSUE TITLE
Can't run az iot hub monitor-events anymore

### ISSUE THREAD

**Issue by Ehill40** [Azure/azure-iot-cli-extension#261] opened 2020-10-16 18:52 UTC
## Describe the bug

**Command Name**
`az iot hub monitor-events
Extension Name: azure-iot. Version: 0.10.3.`

**Errors:**
```
invalid syntax (central_handler.py, line 43)
Traceback (most recent call last):
python3.5/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 711, in _run_job
    six.reraise(*sys.exc_info())
...
azext_iot/monitor/handlers/__init__.py, ln 8, in <module>
    from azext_iot.monitor.handlers.central_handler import CentralHandler
azext_iot/monitor/handlers/central_handler.py, ln 43
    self._issues: List[Issue] = []
                ^
SyntaxError: invalid syntax
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub monitor-events --hub-name {} --device-id {}`

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-Ubuntu-16.04-xenial (Cloud Shell)
Python 3.5.2
Installer: PIP

azure-cli 2.13.0

Extensions:
azure-iot 0.10.3

```

**Comment by c-ryan-k** [comment] 2020-10-16 22:30
@Ehill40  - I just failed to reproduce this in a new cloud shell instance. However, it looks like there might be an issue with python versions here. In my environment, the OS python version (`3.5.2`) is at odds with the azure cli version (`3.6.10`) - and this statement does seem to have issues in `3.5.2`

Could you share the results of running `az --version`, specifically the Python version and location?

Here's mine, as an example:
```
ryan@Azure:~$ az --version
azure-cli                         2.13.0

core                              2.13.0
telemetry                          1.0.6

Extensions:
azure-iot                         0.10.3

Python location '/opt/az/bin/python3'
Extensions directory '/home/ryan/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.6/site-packages/azure-cli-extensions'

Python (Linux) 3.6.10 (default, Oct  9 2020, 12:02:50)
[GCC 5.4.0 20160609]
```

**Comment by c-ryan-k** [comment] 2020-10-29 16:55
@Ehill40 - we've released a new version of the extension that should prevent installs of this extension in environments running python <= `3.6` - which I believe was part of the issue here. 

I'm going to close this for now, if you reinstall the extension and still experience the issue, please re-open and let us know.

**Closed by c-ryan-k** 2020-10-29 16:55 UTC
