### ISSUE TITLE
The behavior of this command has been altered by the following extension: azure-cli-iot-ext

### ISSUE THREAD

**Issue by jongio** [Azure/azure-iot-cli-extension#52] opened 2018-10-23 23:40 UTC
Cloud Shell

Run `az iot hub show-connection-string --hub-name jongiot`

And the you the "the behavior" error message.

Sounds wrong.
```
jon@Azure:~$ az iot hub show-connection-string --hub-name jongiot
The behavior of this command has been altered by the following extension: azure-cli-iot-ext
No IoT Hub found with name jongiot in current subscription.
```

**Comment by digimaun** [comment] 2018-10-30 18:14
This warning happens when an extension overrides a command already provided by a standard command module.

A while ago, during the early stages of extension development, I brought up this behavior with the CLI team and we created an issue to track. The issue was closed with the conclusion being this is by design and we would revisit at some point.

See this issue:
https://github.com/Azure/azure-cli/issues/4712

**Comment by digimaun** [comment] 2020-03-18 18:41
Closing this issue as its being tracked in the azure-cli repo.

**Closed by digimaun** 2020-03-18 18:41 UTC
