### ISSUE TITLE
Property or Tag value should be maximum 512 bytes.

### ISSUE THREAD

**Issue by diirib** [Azure/azure-iot-cli-extension#62] opened 2018-12-20 15:54 UTC
When creating an iotedge deployment, I get the following message: 
'ErrorCode:ArgumentInvalid;Property or Tag value should be maximum 512 bytes.'

AFAIK, with the newest version of iotedge (1.0.5), the size limit for properties is 4Kb, and I've actually tried to create the same deployment manually in the portal and it worked correctly.

I'm using azure-cli-iot-ext (0.6.1)

**Comment by digimaun** [comment] 2019-12-04 22:30
Sorry for the long delayed response. This shouldn't be a problem anymore. In the past it was probably caused by the CLI pointing to an older IoT Hub API version.

Closing the issue. Please comment if you run into problems.

**Closed by digimaun** 2019-12-04 22:30 UTC
