### ISSUE TITLE
Unable to access blob storage account

### ISSUE THREAD

**Issue by Spyntek** [Azure/azure-iot-cli-extension#93] opened 2019-09-12 18:19 UTC
## Describe the bug

**Command Name**
`az iot hub device-identity export
Extension Name: azure-cli-iot-ext. Version: 0.7.1.`

**Errors:**
```
Unable to access blob. If you contact a support representative please include this correlation identifier: 98677835-c20b-4bf4-84b2-7824fd78f4f9, timestamp: 2019-09-12 18:15:32Z, errorcode: IH400007.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-identity export --bcu {} -n {} --ik {} -g {}`

## Environment Summary
```
Windows-10-10.0.18980-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.73
azure-cli-iot-ext 0.7.1

Extensions:
alias 0.5.2
azure-cli-iot-ext 0.7.1
azure-devops 0.12.0
interactive 0.4.3
storage-preview 0.2.7
vm-repair 0.1.1
webapp 0.2.19

```
## Additional Context

I used this to generate the SAS token
$azstgsas = az storage blob generate-sas --account-name $azstgacnt.name -c $azcontainer.name -n $azblob.name --https-only --permissions rwdc --start $start --expiry $end --full-uri

and here is the acutal command for the export

az iot hub device-identity export --bcu $azstgsas -n $aziothub.name --ik true -g $rg

**Comment by digimaun** [comment] 2020-01-09 22:12
The reason this is happening is because the SAS URI generated is for a blob, when in-fact it needs to be a blob container. IoT Hub will generate the blob in the container with the devices payload.

If you run the help for the IoT extension on this command: "az iot hub device-identity export --help" both the description and argument for the SAS URI (--blob-container-uri) mention its for a blob container.

One more point of evidence is the public REST documentation which the property in question is labeled exportBlobContainerUri.

https://docs.microsoft.com/en-us/rest/api/iothub/iothubresource/exportdevices

Using a blob container SAS URI you should not have issues running the export command. If you run with a blob SAS URI the issue is repro'd.

**Comment by digimaun** [comment] 2020-01-10 02:36
I'm going to close this because there is a clear path for resolution (generate a blob container SAS URI instead of blob SAS URI). If you are still running into issues, comment here and we can re-open. Thank you and sorry for the delay in answer.

**Closed by digimaun** 2020-01-10 02:36 UTC

**Comment by kensykora** [comment] 2021-07-13 18:45
Anyone that stumbles upon this issue, for me the error was because I did not have the file named `devices.txt` properly (I had named it `devices.json`) and was giving the input directly to the file and not the container.
