### ISSUE TITLE
TypeError: unrecognized kwargs: ['is_preview'] when loading azure-cli-iot-ext v0.8.0

### ISSUE THREAD

**Issue by Kelerei** [Azure/azure-iot-cli-extension#85] opened 2019-08-14 00:46 UTC
Hello,

We have an automated script run out of our CD server that performs (amongst other things) the following two commands:

```
az extension add --name azure-cli-iot-ext
az iot hub device-identity list --hub-name $HubName
```

Since the v0.8.0 release, the second command always fails.  The relevant output from the debug logs are:

```
23:36:31   Error    |       WARNING: Unable to load extension 'azure-cli-iot-ext'. Use --debug for more information.
23:36:31   Error    |       DEBUG: Traceback (most recent call last):
23:36:31   Error    |       File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\__init__.py", line 183, in _update_command_table_from_extensions
23:36:31   Error    |       File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 614, in _load_extension_command_loader
23:36:31   Error    |       File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 600, in _load_command_loader
23:36:31   Error    |       File "C:\Octopus\Work\20190813233551-69003-5310\azure-cli\cliextensions\azure-cli-iot-ext\azext_iot\__init__.py", line 39, in load_command_table
23:36:31   Error    |       load_command_table(self, args)
23:36:31   Error    |       File "C:\Octopus\Work\20190813233551-69003-5310\azure-cli\cliextensions\azure-cli-iot-ext\azext_iot\commands.py", line 77, in load_command_table
23:36:31   Error    |       with self.command_group('iot hub distributed-tracing', command_type=iothub_ops, is_preview=True) as cmd_group:
23:36:31   Error    |       File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\__init__.py", line 398, in command_group
23:36:31   Error    |       File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 714, in __init__
23:36:31   Error    |       File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 738, in _merge_kwargs
23:36:31   Error    |       File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 689, in _merge_kwargs
23:36:31   Error    |       TypeError: unrecognized kwargs: ['is_preview']
```

Loading the previous version, 0.7.1, works fine.

The Azure CLI version is 2.0.43.

What could be the cause of this issue?

**Comment by digimaun** [comment] 2019-08-14 02:50
It's being caused by the base Azure CLI version (v2.0.43 in your environment) - is it possible for you to upgrade to the latest Azure CLI?

**Comment by digimaun** [comment] 2019-08-14 03:02
A fix for this issue is in the works.

**Comment by digimaun** [comment] 2019-08-14 05:39
@Kelerei please try again, this issue should be resolved.

**Comment by digimaun** [comment] 2019-08-14 17:01
Closing issue for now. Please re-open if you are still having problems. To be clear the fix should resolve the errors you ran into without any change on your side.

**Closed by digimaun** 2019-08-14 17:01 UTC

**Comment by Kelerei** [comment] 2019-08-14 22:58
Sorry for the late reply (was night time in UTC+12).  Can confirm that the issue is fixed on my side -- thanks!

**Comment by digimaun** [comment] 2019-08-15 00:52
Appreciate you closing the loop on this.
